---
name: Test-Kit
version: 0.01
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: Build custom test packages with only the features you want.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  base: 2.11
  namespace::clean: 0.08
provides:
  Test::Kit:
    file: lib/Test/Kit.pm
    version: 0.01
  Test::Kit::Features:
    file: lib/Test/Kit/Features.pm
  Test::Kit::Result:
    file: lib/Test/Kit/Features.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
